### PR TITLE
Make `noarch`

### LINKED ISSUE #3: Use `noarch`
xref https://github.com/conda-forge/cuda-feedstock/issues/4

> As this package doesn't have any architecture dependency on its own, it would make sense to make this noarch. This would allow this package to be built once and reused on other architectures/OSes, which would simply the release process and cutdown on resource usage. For dependencies that are architecture/OS dependent, the right package would be pulled in. Raising to track evaluating this option

### PR DESCRIPTION
**Pull request by adibbley**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #3

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by adibbley** [comment]
Requires https://github.com/conda-forge/cuda-libraries-feedstock/pull/5

**Comment by adibbley** [comment]
@conda-forge-admin , please restart ci

**Review by jakirkham — APPROVED** [review]
Thanks Alex! 🙏

**Pull request merged**
